-- ----------------------------------------------------------------------------
-- xmake.lua for Tiny C Compiler (tinycc-mob)
-- ----------------------------------------------------------------------------

set_project("tinycc")
set_version("0.9.28rc")
set_languages("c99")

-- ----------------------------------------------------------------------------
-- options
-- ----------------------------------------------------------------------------
option("static")
    set_default(true)
    set_description("Build libtcc as static library")
option_end()

option("debug")
    set_default(false)
    set_description("Enable debug build")
option_end()

option("backtrace")
    set_default(true)
    set_description("Enable backtrace support")
option_end()

option("bcheck")
    set_default(true)
    set_description("Enable bounds checking support")
option_end()

-- ----------------------------------------------------------------------------
-- helper: detect native target string (arch-os)
-- ----------------------------------------------------------------------------
local function native_target()
    local arch = os.arch()
    local archmap = {
        x86_64 = "x86_64", x64 = "x86_64",
        i386 = "i386", x86 = "i386",
        arm64 = "arm64", aarch64 = "arm64",
        arm = "arm",
        riscv64 = "riscv64",
    }
    arch = archmap[arch] or arch
    if is_plat("windows") then
        return arch .. "-win32"
    elseif is_plat("macosx") then
        return arch .. "-osx"
    else
        return arch
    end
end

-- ----------------------------------------------------------------------------
-- generate config.h and tccdefs_.h before any target is built
-- ----------------------------------------------------------------------------
on_load(function ()
    local projdir = os.projectdir()

    -- tccdefs_.h: convert include/tccdefs.h to a C string table
    local tccdefs_h = path.join(projdir, "tccdefs_.h")
    if not os.isfile(tccdefs_h) then
        local c2str_src = path.join(projdir, "conftest.c")
        local c2str_bin = path.join(projdir, "c2str")
        if is_plat("windows") then c2str_bin = c2str_bin .. ".exe" end
        if not os.isfile(c2str_bin) then
            local cc = os.getenv("CC") or "cc"
            os.execv(cc, {"-DC2STR", c2str_src, "-o", c2str_bin})
        end
        os.execv(c2str_bin, {path.join(projdir, "include", "tccdefs.h"), tccdefs_h})
        print("[xmake] generated tccdefs_.h")
    end

    -- only generate config.h if missing (user may have run ./configure themselves)
    local cfg_h = path.join(projdir, "config.h")
    if os.isfile(cfg_h) then return end

    local T = native_target()
    local lines = {
        "/* Generated by xmake.lua - do not modify */",
        "",
        '#define TCC_VERSION "0.9.28rc"',
        "",
    }

    -- target-specific block (guarded so cross-compiler objects can override)
    local target_block = {}
    if T == "x86_64-osx" or T == "arm64-osx" then
        table.insert(target_block, "#define TCC_TARGET_MACHO 1")
        table.insert(target_block, "#define CONFIG_DWARF_VERSION 4")
        table.insert(target_block, "#define CONFIG_CODESIGN 1")
        -- SDK path (best effort)
        local sdk = try { function()
            return os.iorunv("xcrun", {"--show-sdk-path"})
        end }
        if sdk then
            sdk = sdk:trim()
            table.insert(target_block, string.format('#define CONFIG_USR_INCLUDE "%s/usr/include"', sdk))
        end
    elseif T == "x86_64" or T == "i386" then
        -- nothing extra needed for Linux x86
    elseif T == "arm64" then
        -- nothing extra needed for Linux arm64
    end

    if is_plat("macosx") or is_plat("linux") or is_plat("bsd") then
        -- emit a guarded block (same pattern as configure output)
        local guard_archs = "TCC_TARGET_I386 || TCC_TARGET_X86_64 || TCC_TARGET_ARM || TCC_TARGET_ARM64 || TCC_TARGET_RISCV64 || TCC_TARGET_C67"
        table.insert(lines, "#if !(" .. guard_archs .. ")")
        if T == "x86_64"     then table.insert(lines, "#define TCC_TARGET_X86_64 1")
        elseif T == "i386"   then table.insert(lines, "#define TCC_TARGET_I386 1")
        elseif T == "arm64-osx" or T == "arm64" then
                                   table.insert(lines, "#define TCC_TARGET_ARM64 1")
        elseif T == "x86_64-osx" then
                                   table.insert(lines, "#define TCC_TARGET_X86_64 1")
        elseif T == "arm"    then table.insert(lines, "#define TCC_TARGET_ARM 1")
        end
        for _, l in ipairs(target_block) do table.insert(lines, l) end
        table.insert(lines, "#endif")
        table.insert(lines, "")
    end

    -- install dir (default)
    table.insert(lines, "#ifndef CONFIG_TCCDIR")
    if is_plat("windows") then
        table.insert(lines, '#define CONFIG_TCCDIR "C:/tcc"')
    else
        table.insert(lines, '#define CONFIG_TCCDIR "/usr/local/lib/tcc"')
    end
    table.insert(lines, "#endif")
    table.insert(lines, "#define CONFIG_TCC_PREDEFS 1")
    table.insert(lines, "")

    io.writefile(cfg_h, table.concat(lines, "\n"))
    print("[xmake] generated " .. cfg_h)
end)

-- ----------------------------------------------------------------------------
-- per-target defines (macros that select arch/OS backend)
-- ----------------------------------------------------------------------------
local target_defines = {
    ["i386"]            = { "TCC_TARGET_I386" },
    ["i386-win32"]      = { "TCC_TARGET_I386",   "TCC_TARGET_PE" },
    ["x86_64"]          = { "TCC_TARGET_X86_64" },
    ["x86_64-win32"]    = { "TCC_TARGET_X86_64", "TCC_TARGET_PE" },
    ["x86_64-osx"]      = { "TCC_TARGET_X86_64", "TCC_TARGET_MACHO" },
    ["arm"]             = { "TCC_TARGET_ARM", "TCC_ARM_VFP", "TCC_ARM_EABI", "TCC_ARM_HARDFLOAT" },
    ["arm-wince"]       = { "TCC_TARGET_ARM", "TCC_ARM_VFP", "TCC_ARM_EABI", "TCC_ARM_HARDFLOAT", "TCC_TARGET_PE" },
    ["arm64"]           = { "TCC_TARGET_ARM64" },
    ["arm64-osx"]       = { "TCC_TARGET_ARM64", "TCC_TARGET_MACHO" },
    ["riscv64"]         = { "TCC_TARGET_RISCV64" },
    ["c67"]             = { "TCC_TARGET_C67" },
}

-- per-target extra source files (beyond the shared core)
local target_sources = {
    ["i386"]         = { "i386-gen.c",    "i386-link.c",    "i386-asm.c" },
    ["i386-win32"]   = { "i386-gen.c",    "i386-link.c",    "i386-asm.c",    "tccpe.c" },
    ["x86_64"]       = { "x86_64-gen.c",  "x86_64-link.c",  "i386-asm.c" },
    ["x86_64-win32"] = { "x86_64-gen.c",  "x86_64-link.c",  "i386-asm.c",    "tccpe.c" },
    ["x86_64-osx"]   = { "x86_64-gen.c",  "x86_64-link.c",  "i386-asm.c",    "tccmacho.c" },
    ["arm"]          = { "arm-gen.c",     "arm-link.c",     "arm-asm.c" },
    ["arm-wince"]    = { "arm-gen.c",     "arm-link.c",     "arm-asm.c",     "tccpe.c" },
    ["arm64"]        = { "arm64-gen.c",   "arm64-link.c",   "arm64-asm.c" },
    ["arm64-osx"]    = { "arm64-gen.c",   "arm64-link.c",   "arm64-asm.c",   "tccmacho.c" },
    ["riscv64"]      = { "riscv64-gen.c", "riscv64-link.c", "riscv64-asm.c" },
    ["c67"]          = { "c67-gen.c",     "c67-link.c",     "tcccoff.c" },
}

-- core source files shared by every target
local core_sources = {
    "libtcc.c", "tccpp.c", "tccgen.c", "tccdbg.c",
    "tccelf.c", "tccasm.c", "tccrun.c",
}

-- ----------------------------------------------------------------------------
-- helper applied to both libtcc and tcc targets
-- ----------------------------------------------------------------------------
local function apply_common(T)
    add_includedirs(".", "include")

    local defs = target_defines[T] or {}
    for _, d in ipairs(defs) do add_defines(d) end

    if is_plat("windows") then add_defines("TCC_TARGET_PE") end
    if is_plat("macosx")  then add_defines("TARGETOS_Darwin") end
    if is_plat("linux")   then add_defines("TARGETOS_Linux")  end

    if is_plat("linux", "bsd") then
        add_syslinks("m", "dl", "pthread")
    end

    -- MSVC defaults to C++ mode; force C compilation for TCC sources
    if is_plat("windows") then
        add_cflags("/TC", {force = true})
    end

    if has_config("debug") then
        set_symbols("debug")
        set_optimize("none")
    else
        set_optimize("faster")
    end
end

-- ----------------------------------------------------------------------------
-- libtcc  (static or shared)
-- ----------------------------------------------------------------------------
target("libtcc")
    local T = native_target()
    local extra_srcs = target_sources[T] or {}

    -- libtcc = core - {tcc.c, tcctools.c} + target-specific
    local srcs = table.clone(core_sources)
    for _, f in ipairs(extra_srcs) do table.insert(srcs, f) end
    add_files(table.unpack(srcs))
    add_headerfiles("*.h", "*.def")

    if has_config("static") then
        set_kind("static")
    else
        set_kind("shared")
        add_cflags("-fPIC")
        add_ldflags("-fPIC")
    end

    add_defines("ONE_SOURCE=0")

    -- clang/x86_64: fPIC avoids 32-bit relocs inside the archive
    if is_arch("x86_64") then
        add_cflags("-fPIC")
    end

    apply_common(T)
target_end()

-- ----------------------------------------------------------------------------
-- tcc executable
-- ----------------------------------------------------------------------------
target("tcc")
    set_kind("binary")
    set_default(false)
    add_files("tcc.c")
    add_deps("libtcc")
    add_defines("ONE_SOURCE=0")

    local T = native_target()
    apply_common(T)

    if is_plat("macosx") then
        add_ldflags("-flat_namespace", {force = true})
    end

    -- embed git hash if available
    on_load(function(target)
        local hash = try { function()
            return os.iorunv("git", {"log", "-1", "--date=short", "--pretty=format:%cd mob@%h"})
        end }
        if hash then
            local dirty = ""
            local ok = try { function() os.execv("git", {"diff", "--quiet"}) return true end }
            if not ok then dirty = "*" end
            target:add("defines", 'TCC_GITHASH="' .. hash:trim() .. dirty .. '"')
        end
    end)
target_end()

-- ----------------------------------------------------------------------------
-- cross-compiler targets   (e.g.  xmake build x86_64-tcc)
-- ----------------------------------------------------------------------------
local cross_targets = {
    "i386", "x86_64", "i386-win32", "x86_64-win32", "x86_64-osx",
    "arm", "arm64", "arm-wince", "riscv64", "arm64-osx", "c67",
}

for _, ct in ipairs(cross_targets) do
    target(ct .. "-tcc")
        set_kind("binary")
        set_default(false)
        -- cross compilers are traditionally built from a single source
        add_files("tcc.c")
        add_includedirs(".", "include")
        add_defines("ONE_SOURCE=1")
        add_defines('TCC_CROSSPREFIX="' .. ct .. '-"')
        local defs = target_defines[ct] or {}
        for _, d in ipairs(defs) do add_defines(d) end
        if is_plat("linux", "bsd") then
            add_syslinks("m", "dl", "pthread")
        end
        if is_plat("macosx") then
            add_ldflags("-flat_namespace", {force = true})
        end
        if has_config("debug") then
            set_symbols("debug")
        else
            set_optimize("faster")
        end
        set_filename(ct .. "-tcc")
    target_end()
end

-- ----------------------------------------------------------------------------
-- libtcc1.a  – the TCC runtime library, compiled *by* tcc itself
-- ----------------------------------------------------------------------------
target("libtcc1")
    set_kind("phony")
    set_default(false)
    add_deps("tcc")

    on_build(function(target)
        local tcc_bin  = target:dep("tcc"):targetfile()
        local src_lib  = path.join(os.projectdir(), "lib")
        local src_win  = path.join(os.projectdir(), "win32", "lib")
        local outdir   = path.join(target:targetdir())
        local T        = native_target()

        -- object sets per target
        -- Note: alloca is .S (assembly), not .c
        local common_o = {
            "libtcc1.c", "stdatomic.c", "atomic.S",
            "builtin.c", "alloca.S", "alloca-bt.S",
            "runmain.c", "tcov.c", "bt-exe.c", "bt-log.c",
        }
        if has_config("bcheck") then
            table.insert(common_o, "bcheck.c")
        end

        local obj_map = {
            ["i386"]         = { "libtcc1.c", "pic86.S", "dsohandle.c" },
            ["x86_64"]       = { "libtcc1.c", "dsohandle.c" },
            ["x86_64-osx"]   = { "libtcc1.c" },
            ["arm64"]        = { "lib-arm64.c", "dsohandle.c" },
            ["arm64-osx"]    = { "lib-arm64.c" },
            ["arm"]          = { "libtcc1.c", "armeabi.c", "armflush.c", "dsohandle.c" },
            ["arm-wince"]    = { "libtcc1.c", "armeabi.c", "armflush.c",
                                  "crt1.c","wincrt1.c","dllcrt1.c","dllmain.c" },
            ["i386-win32"]   = { "libtcc1.c", "chkstk.S",
                                  "crt1.c","crt1w.c","wincrt1.c","wincrt1w.c",
                                  "dllcrt1.c","dllmain.c" },
            ["x86_64-win32"] = { "libtcc1.c", "chkstk.S",
                                  "crt1.c","crt1w.c","wincrt1.c","wincrt1w.c",
                                  "dllcrt1.c","dllmain.c" },
            ["riscv64"]      = { "lib-arm64.c", "dsohandle.c" },
        }

        local srcs = obj_map[T] or {}
        local seen = {}
        for _, f in ipairs(srcs) do seen[f] = true end
        for _, f in ipairs(common_o) do
            if not seen[f] then table.insert(srcs, f) seen[f] = true end
        end

        -- objects that are installed standalone, not packed into libtcc1.a
        local extra_set = {}
        for _, f in ipairs({"runmain.c","bt-exe.c","bt-dll.c","bt-log.c","bcheck.c"}) do
            extra_set[f] = true
        end

        os.mkdir(outdir)

        local obj_files  = {}
        local extra_objs = {}

        local xflags = {
            "-B", os.projectdir(),
            "-I", path.join(os.projectdir(), "include"),
            "-I", os.projectdir(),
        }
        -- on macOS: pass the SDK sysroot so tcc can find system headers
        if is_plat("macosx") then
            local sdk = try { function() return os.iorunv("xcrun", {"--show-sdk-path"}) end }
            if sdk then
                sdk = sdk:trim()
                table.insert(xflags, "-isystem")
                table.insert(xflags, sdk .. "/usr/include")
            end
        end
        -- on Linux: help tcc find glibc internal headers (bits/*, gnu/*)
        if is_plat("linux") then
            local arch = os.arch()
            local multiarch_map = {
                x86_64 = "x86_64-linux-gnu",
                x64    = "x86_64-linux-gnu",
                arm64  = "aarch64-linux-gnu",
                aarch64 = "aarch64-linux-gnu",
                i386   = "i386-linux-gnu",
                x86    = "i386-linux-gnu",
                arm    = "arm-linux-gnueabihf",
            }
            local triplet = multiarch_map[arch]
            if triplet then
                local inc = "/usr/include/" .. triplet
                if os.isdir(inc) then
                    table.insert(xflags, "-I")
                    table.insert(xflags, inc)
                end
            end
        end

        for _, src in ipairs(srcs) do
            local srcpath = path.join(src_lib, src)
            if not os.isfile(srcpath) then
                srcpath = path.join(src_win, src)
            end
            if not os.isfile(srcpath) then
                cprint("${yellow}[libtcc1]${reset} skip missing: " .. src)
                goto continue
            end
            local objname = path.join(outdir, src:gsub("[./\\]", "_") .. ".o")
            os.execv(tcc_bin, table.join({"-c", srcpath, "-o", objname}, xflags))

            if extra_set[src] then
                local dest = path.join(outdir, path.basename(src):gsub("%.[^.]+$","") .. ".o")
                os.cp(objname, dest)
                table.insert(extra_objs, dest)
            else
                table.insert(obj_files, objname)
            end
            ::continue::
        end

        local ar_out = path.join(outdir, "libtcc1.a")
        os.execv(tcc_bin, table.join({"-ar", "rcs", ar_out}, obj_files))
        cprint("${green}[libtcc1]${reset} " .. ar_out)
    end)
target_end()

-- ----------------------------------------------------------------------------
-- install
-- ----------------------------------------------------------------------------
target("install-tcc")
    set_kind("phony")
    set_default(false)
    add_deps("tcc", "libtcc", "libtcc1")

    on_build(function(target)
        local prefix  = get_config("prefix") or "/usr/local"
        local bindir  = prefix .. "/bin"
        local libdir  = prefix .. "/lib"
        local tccdir  = prefix .. "/lib/tcc"
        local incdir  = prefix .. "/include"
        local bd      = target:dep("tcc"):targetdir()

        os.mkdir(bindir)
        os.mkdir(tccdir)
        os.mkdir(tccdir .. "/include")
        os.mkdir(libdir)
        os.mkdir(incdir)

        -- tcc binary
        os.cp(path.join(bd, "tcc"), bindir)
        -- libtcc
        for _, f in ipairs(os.files(path.join(bd, "libtcc.*"))) do
            os.cp(f, libdir)
        end
        -- libtcc1 + extra objects
        for _, f in ipairs(os.files(path.join(bd, "*.a"))) do
            os.cp(f, tccdir)
        end
        for _, f in ipairs(os.files(path.join(bd, "*.o"))) do
            os.cp(f, tccdir)
        end
        -- headers
        for _, f in ipairs(os.files(path.join(os.projectdir(), "include", "*.h"))) do
            os.cp(f, tccdir .. "/include")
        end
        os.cp(path.join(os.projectdir(), "tcclib.h"), tccdir .. "/include")
        os.cp(path.join(os.projectdir(), "libtcc.h"), incdir)

        cprint("${green}installed${reset} to " .. prefix)
    end)
target_end()
